### ISSUE TITLE
Windows: ModuleNotFoundError: No module named 'dns'

### ISSUE THREAD

**Issue by Narculis** [dhs-ncats/trustymail#148]
# 🐛 Summary #

What's wrong? Please be specific.

Getting this error when trying to run TrustyMail.

C:\Users\brian>trustymail
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\brian\AppData\Local\Programs\Python\Python311\Scripts\trustymail.exe\__main__.py", line 4, in <module>
  File "C:\Users\brian\AppData\Local\Programs\Python\Python311\Lib\site-packages\trustymail\cli.py", line 61, in <module>
    from . import trustymail
  File "C:\Users\brian\AppData\Local\Programs\Python\Python311\Lib\site-packages\trustymail\trustymail.py", line 15, in <module>
    import DNS
  File "C:\Users\brian\AppData\Local\Programs\Python\Python311\Lib\site-packages\DNS\__init__.py", line 70, in <module>
    from dns.version import version as __version__  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'dns'

Fresh install TrustyMail

Run Trustymail

## Expected behavior ##

Trusty Mail runs successfully.

## Any helpful log output or screenshots ##

![image](https://github.com/cisagov/trustymail/assets/49448418/359fb027-1d1b-4425-b6de-266410eca675)

![image](https://github.com/cisagov/trustymail/assets/49448418/b6fd1770-7b63-4de0-85b4-626006c69b1c)

There is a similar bug report for MAC OS, but I am running Windows. I have tried a fresh install on 3 devices, 2 Windows 11, 1 Windows 10.

Each returns the same error. I have tried installing dnspython, fresh installing python, using older versions of python, etc.

**Comment by jsf9k** [comment]
It's a different OS, but the problem is the same.  The underlying file system is case insensitive (see #41).  The only solutions are to change the Windows file system to be case sensitive (I think this is possible, but I'm not a Windows user) or switch to a different OS.

**Comment by bitpy2023** [comment]
pip install dnspython
