### ISSUE TITLE
"trustmail" GitHub tap not found....?

### ISSUE THREAD

**Issue by mmclean636jr** [dhs-ncats/trustymail#62]
**MMcLeans-MacBook-Air:trustymail mmclean$ brew install trustymail**
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
bareos-client                            shelltestrunner
==> Updated Formulae
angular-cli         frugal              mariadb@10.0        terraform
ansible             grpc                mas                 tig
azure-cli           haxe                minimal-racket      vapoursynth
bash                heroku              node                vim
bazel               hugo                pandoc-citeproc     wpcli-completion
bfg                 isc-dhcp            re2                 wtf
cayley              joplin              rom-tools           xtensor
ccm                 kitchen-sync        sbcl                yaml-cpp
cjdns               knot-resolver       skafos              zanata-client
emscripten          libhttpseverywhere  sslh                zimg
feh                 mame                telegraf
==> Deleted Formulae
qt@5.7

**Error: No available formula with the name "trustymail" 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.**

**Comment by jsf9k** [comment]
Thanks for the issue, @mmclean636jr!  I'm not an OSX guy, but could the problem be that you're trying to install via `brew`?  We don't maintain a `brew` tap for `trustymail`, so I don't think that will work.

You can, however, install the latest published `trustymail` via `pip`:
```
pip install trustymail
```
If you prefer to install the very latest `trustymail` code from GitHub, you can do that via `pip` as well:
```
pip install git+https://github.com/dhs-ncats/trustymail.git@develop
```

I'd recommend using `pip` instead of `brew`.

**Comment by mmclean636jr** [comment]
I have been having real issues with using "pip" recently.

Constantly blows up. Thats why I tried to use Homebrew.

Any suggestion>?

**MMcLeans-MacBook-Air:~ mmclean$ pip install git+https://github.com/dhs-ncats/trustymail.git@develop**
>>Collecting git+https://github.com/dhs-ncats/trustymail.git@develop
 >> Cloning https://github.com/dhs-ncats/trustymail.git (to develop) to /private/var/folders/db/4x89tk6n39j7stzbmphn9yv40000gp/T/pip-y12BpE-build
>>Collecting requests (from trustymail==0.5.4.dev0)
  >>Using cached requests-2.18.4-py2.py3-none-any.whl
>>Collecting docopt (from trustymail==0.5.4.dev0)
 >> Using cached docopt-0.6.2.tar.gz
>>Collecting publicsuffix (from trustymail==0.5.4.dev0)
  >>Using cached publicsuffix-1.1.0.tar.gz
>>Collecting dnspython (from trustymail==0.5.4.dev0)
 >> Using cached dnspython-1.15.0-py2.py3-none-any.whl
>>Collecting py3dns (from trustymail==0.5.4.dev0)
 >> Using cached py3dns-3.1.0.tar.gz
    **Complete output from command python setup.py egg_info:**
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/db/4x89tk6n39j7stzbmphn9yv40000gp/T/pip-build-GxtTYv/py3dns/setup.py", line 7, in <module>
        import DNS
      File "/private/var/folders/db/4x89tk6n39j7stzbmphn9yv40000gp/T/pip-build-GxtTYv/py3dns/DNS/__init__.py", line 21, in <module>
        raise Exception("py3dns 3.1 requires either ipaddress (python3.3) or ipaddr, see CHANGES for 3.1.0")
    Exception: py3dns 3.1 requires either ipaddress (python3.3) or ipaddr, see CHANGES for 3.1.0
    
    ----------------------------------------
**Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/db/4x89tk6n39j7stzbmphn9yv40000gp/T/pip-build-GxtTYv/py3dns/**

**Comment by jsf9k** [comment]
Note that if you're running on OSX you will almost certainly suffer from the (unresolved) issue #41.

I'll have to look into the other `pip` issue you're seeing.

**Comment by jsf9k** [comment]
@mmclean636jr, what version of Python are you using?  I think that may be part of the issue.

**Comment by mmclean636jr** [comment]
MMcLeans-MacBook-Air:~ mmclean$ python --version
Python 2.7.14

**Comment by mmclean636jr** [comment]
Just for further testing purposes, I tried to install the tool on a personal PC with Python 3.6 and received the same error.


C:\Users\Michael McLean\Documents\PIP\trustymail-develop>pip install trustymail
Collecting trustymail
  Using cached trustymail-0.3.0.tar.gz
Collecting requests (from trustymail)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting docopt (from trustymail)
  Using cached docopt-0.6.2.tar.gz
Collecting publicsuffix (from trustymail)
  Using cached publicsuffix-1.1.0.tar.gz
Collecting dnspython (from trustymail)
  Using cached dnspython-1.15.0-py2.py3-none-any.whl
Collecting py3dns (from trustymail)
  Using cached py3dns-3.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\MICHAE~1\AppData\Local\Temp\pip-build-v2t44_i8\py3dns\setup
.py", line 7, in <module>
        import DNS
      File "C:\Users\MICHAE~1\AppData\Local\Temp\pip-build-v2t44_i8\py3dns\DNS\_
_init__.py", line 37, in <module>
        Base._DiscoverNameServers()
      File "C:\Users\MICHAE~1\AppData\Local\Temp\pip-build-v2t44_i8\py3dns\DNS\B
ase.py", line 84, in _DiscoverNameServers
        return ParseResolvConf()
      File "C:\Users\MICHAE~1\AppData\Local\Temp\pip-build-v2t44_i8\py3dns\DNS\B
ase.py", line 52, in ParseResolvConf
        with open(resolv_path, 'r') as stream:
    FileNotFoundError: [Errno 2] No such file or directory: '/etc/resolv.conf'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\MICHAE~1
\AppData\Local\Temp\pip-build-v2t44_i8\py3dns\

**Comment by jsf9k** [comment]
@mmclean636jr Apologies for the late response.  I was away on travel the last few weeks.

I don't think py3dns supports Windows.  Are you able to install on a Linux system with python 3?
